= AWS IP address ranges filter

Amazon Web Services (AWS) publishes a list of its https://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html[current IP address ranges].

This RESTful web service allows to filter that list by region prefix, e.g. `EU` or `US`.

== Running the service
The easiest way to run the service is using the official Docker image.
Using `docker run` start the service by executing `docker run --rm -p 8080:8080 timpavone1990/aws-ip-address-range-filter`.

== API
* The OpenAPI definition can be found
** link:specs/aws-ip-address-ranges-filter-v1.0.yaml[in this repository] and
** at the corresponding endpoint of a running service instance: `http(s)://<SERVER>:<PORT>/<CONTEXT_PATH>/v3/api-docs`.
* The service's Swagger UI can be found at `http(s)://<SERVER>:<PORT>/<CONTEXT_PATH>/swagger-ui.html`.
* An example response can be found in the OpenAPI definition and the Swagger UI.

== Observability
* Metrics are recorded in-memory and are exposed at `http(s)://<SERVER>:<PORT>/<CONTEXT_PATH>/metrics`
* The application health status is exposed at `http(s)://<SERVER>:<PORT>/<CONTEXT_PATH>/health`
* General information about the application is exposed at `http(s)://<SERVER>:<PORT>/<CONTEXT_PATH>/info`
