server:
  error:
    include-message: always

clients:
  aws:
    ip-address-ranges:
      url: https://ip-ranges.amazonaws.com/

management:
  endpoints:
    web:
      exposure:
        include: metrics
      base-path: /
