server:
  error:
    include-message: always

clients:
  aws:
    ip-address-ranges:
      url: https://ip-ranges.amazonaws.com/

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /

info:
  app:
    name: ${name}
    description: ${description}
    version: ${version}

feign:
  client:
    config:
      default:
        connectTimeout: 500
        readTimeout: 500
