name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Fetch tags as well.
          fetch-depth: "0"
      - name: Configure git identity
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Release
        run: make release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
